const DATA=window.COMMITTEE_DATA||[]; const TODAY=new Date(); TODAY.setHours(0,0,0,0);
const $=id=>document.getElementById(id); const state={province:'',expertise:'',status:'',duplicate:'',search:''};
const normExp=s=>s.includes('สถาปัตยกรรม')?'ด้านสถาปัตยกรรมหรือด้านวิศวกรรม':s;
const fmt=d=>{if(!d)return'-';const x=new Date(d+'T00:00:00');return x.toLocaleDateString('th-TH',{day:'2-digit',month:'2-digit',year:'numeric'})};
const daysLeft=r=>Math.ceil((new Date(r.expires+'T00:00:00')-TODAY)/86400000);
const statusOf=r=>{let d=daysLeft(r);return d<0?'หมดวาระแล้ว':d<=365?'ใกล้หมดวาระ':'ปกติ'};
function provinceStats(base=DATA){let m={};base.forEach(r=>{(m[r.province]??=[]).push(normExp(r.expertise))});let out={};Object.entries(m).forEach(([p,a])=>{let c={};a.forEach(x=>c[x]=(c[x]||0)+1);let dup=Object.entries(c).filter(x=>x[1]>1);out[p]={dupCount:dup.length,dup}});return out}
const PSTATS=provinceStats();
function fillSelects(){[...new Set(DATA.map(x=>x.province))].sort((a,b)=>a.localeCompare(b,'th')).forEach(x=>$('province').add(new Option(x,x)));[...new Set(DATA.map(x=>normExp(x.expertise)))].sort().forEach(x=>$('expertise').add(new Option(x,x)))}
function filtered(){return DATA.filter(r=>{let ps=PSTATS[r.province]?.dupCount||0;return(!state.province||r.province===state.province)&&(!state.search||r.province.includes(state.search))&&(!state.expertise||normExp(r.expertise)===state.expertise)&&(!state.status||statusOf(r)===state.status)&&(!state.duplicate||(state.duplicate==='none'?ps===0:ps===+state.duplicate))})}
function renderKpis(){let normal=DATA.filter(r=>statusOf(r)==='ปกติ').length,soon=DATA.filter(r=>statusOf(r)==='ใกล้หมดวาระ').length,expired=DATA.filter(r=>statusOf(r)==='หมดวาระแล้ว').length;$('kpis').innerHTML=[['กรรมการทั้งหมด',DATA.length],['สถานะปกติ',normal],['ใกล้หมดวาระ ≤ 1 ปี',soon],['หมดวาระแล้ว',expired]].map(x=>`<div class="kpi"><div class="n">${x[1].toLocaleString()}</div><div class="t">${x[0]}</div></div>`).join('')}
function renderAlerts(){let a=DATA.filter(r=>statusOf(r)!=='ปกติ').sort((x,y)=>daysLeft(x)-daysLeft(y));$('alertCount').textContent=a.length;$('alerts').innerHTML=a.map(r=>`<div class="alert ${daysLeft(r)<0?'expired':''}"><b>${r.name}</b><br>${r.province} • ${fmt(r.expires)}<br><span>${daysLeft(r)<0?`เกินกำหนด ${Math.abs(daysLeft(r)).toLocaleString()} วัน`:`เหลือ ${daysLeft(r).toLocaleString()} วัน`}</span></div>`).join('')||'<span class="hint">ไม่มีรายการแจ้งเตือน</span>'}
let MAP_GEO=null,MAP_LOADING=false;
function mapColor(n,active=false){if(active)return '#2f6f69';if(n>=3)return '#75b9b3';if(n===2)return '#9fd3c0';if(n===1)return '#c4e4cf';return '#e2f1dd'}
function mapFallback(){let prov=[...new Set(DATA.map(r=>r.province))].sort((a,b)=>a.localeCompare(b,'th'));$('provinceMap').innerHTML='<div class="map-error">ไม่สามารถโหลดเส้นขอบแผนที่ได้ จึงแสดงรายชื่อจังหวัดแทน</div><div class="province-map-fallback">'+prov.map(p=>`<button class="province-chip ${state.province===p?'active':''}" data-p="${p}">${p}</button>`).join('')+'</div>';document.querySelectorAll('.province-chip').forEach(b=>b.onclick=()=>selectProvince(b.dataset.p))}
function selectProvince(p){state.province=state.province===p?'':p;$('province').value=state.province;render()}
function geoPaths(geom,project){let polys=geom.type==='Polygon'?[geom.coordinates]:geom.coordinates;return polys.map(poly=>poly.map(ring=>'M'+ring.map(([x,y])=>project(x,y).join(',')).join('L')+'Z').join('')).join('')}
function drawThailandMap(geo){let el=$('provinceMap'),w=620,h=650,pad=18,pts=[];geo.features.forEach(f=>{let g=f.geometry,c=g.type==='Polygon'?[g.coordinates]:g.coordinates;c.forEach(poly=>poly.forEach(r=>r.forEach(p=>pts.push(p))))});let xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),scale=Math.min((w-2*pad)/(maxX-minX),(h-2*pad)/(maxY-minY)),ox=(w-(maxX-minX)*scale)/2,oy=(h-(maxY-minY)*scale)/2;let project=(x,y)=>[ox+(x-minX)*scale,h-(oy+(y-minY)*scale)];let paths=geo.features.map(f=>{let p=f.properties||{},name=p.ADM1_TH||p.NL_NAME_1||p.name_th||'',n=PSTATS[name]?.dupCount||0,active=state.province===name;return `<path class="thai-province${active?' selected':''}" data-p="${name}" d="${geoPaths(f.geometry,project)}" fill="${mapColor(n,active)}"><title>${name} • ${n?`ซ้ำ ${n} สาขา`:'ไม่ซ้ำสาขา'} — คลิกเพื่อกรองข้อมูล</title></path>`}).join('');el.innerHTML=`<div class="map-shell"><svg class="thailand-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="แผนที่ประเทศไทย 77 จังหวัด">${paths}</svg><div class="map-legend"><span><i style="background:#e2f1dd"></i>ไม่ซ้ำ</span><span><i style="background:#c4e4cf"></i>ซ้ำ 1 สาขา</span><span><i style="background:#9fd3c0"></i>ซ้ำ 2 สาขา</span><span><i style="background:#75b9b3"></i>ซ้ำมากกว่า 2 สาขา</span></div><div class="map-selected">${state.province?'จังหวัดที่เลือก: <b>'+state.province+'</b>':'คลิกจังหวัดบนแผนที่เพื่อกรองข้อมูล'}</div></div>`;el.querySelectorAll('.thai-province').forEach(x=>x.onclick=()=>selectProvince(x.dataset.p))}
function renderMap(){
  if(MAP_GEO){drawThailandMap(MAP_GEO);return}
  if(MAP_LOADING)return;
  MAP_LOADING=true;
  $('provinceMap').innerHTML='<div class="map-loading">กำลังโหลดแผนที่ประเทศไทย…</div>';
  fetch('./thailand-provinces.geojson',{cache:'no-store'})
    .then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()})
    .then(g=>{MAP_GEO=g;MAP_LOADING=false;drawThailandMap(g)})
    .catch(()=>{MAP_LOADING=false;mapFallback()});
}
function renderDup(){let entries=Object.entries(PSTATS);let n0=entries.filter(x=>x[1].dupCount===0).length,n2=entries.filter(x=>x[1].dupCount===2).length,n3=entries.filter(x=>x[1].dupCount>=3).length;$('dupSummary').innerHTML=`<div class="summary"><strong>${n0}</strong>ไม่ซ้ำสาขา</div><div class="summary"><strong>${n2}</strong>ซ้ำ 2 สาขา</div><div class="summary"><strong>${n3}</strong>ซ้ำ 3 สาขา</div>`;$('dupTable').innerHTML=entries.filter(x=>x[1].dupCount>0).sort((a,b)=>b[1].dupCount-a[1].dupCount).map(([p,s])=>`<tr><td>${p}</td><td>${s.dupCount>=3?'ซ้ำ 3 สาขา':'ซ้ำ 2 สาขา'}</td><td>${s.dup.map(x=>`${x[0].replace('ด้าน','')} (${x[1]})`).join('<br>')}</td></tr>`).join('')||'<tr><td colspan="3">ไม่พบจังหวัดที่ซ้ำสาขา</td></tr>'}
function renderYears(rows){let m={};rows.forEach(r=>{let a=new Date(r.appointed).getFullYear()+543,e=new Date(r.expires).getFullYear()+543;(m[a]??={a:0,e:0}).a++;(m[e]??={a:0,e:0}).e++});let max=Math.max(1,...Object.values(m).flatMap(x=>[x.a,x.e]));$('yearChart').innerHTML=Object.keys(m).sort().map(y=>`<div class="bar-row"><span>พ.ศ. ${y}</span><div><div class="bar-track" title="แต่งตั้ง ${m[y].a}"><div class="bar-fill" style="width:${m[y].a/max*100}%"></div></div><div class="bar-track" style="margin-top:3px" title="ครบวาระ ${m[y].e}"><div class="bar-fill" style="width:${m[y].e/max*100}%;background:linear-gradient(90deg,#d9b8dc,#e5c5b4)"></div></div></div><b>${m[y].a}/${m[y].e}</b></div>`).join('')+'<p class="hint">ตัวเลขด้านขวา = แต่งตั้ง / ครบวาระ</p>'}
function renderExpert(rows){let m={};rows.forEach(r=>m[normExp(r.expertise)]=(m[normExp(r.expertise)]||0)+1);let colors=['#9fcdb6','#a8c9dc','#c7b5dd','#e3b6a4'];let total=Object.values(m).reduce((a,b)=>a+b,0)||1,acc=0,stops=[];Object.values(m).forEach((v,i)=>{let s=acc/total*360;acc+=v;let e=acc/total*360;stops.push(`${colors[i%colors.length]} ${s}deg ${e}deg`)});$('expertChart').innerHTML=`<div class="donut-wrap"><div class="donut" style="background:conic-gradient(${stops.join(',')})"></div><div class="legend">${Object.entries(m).map(([k,v],i)=>`<div><span class="dot" style="background:${colors[i%colors.length]}"></span>${k.replace('ด้าน','')} <b>${v}</b> (${(v/total*100).toFixed(1)}%)</div>`).join('')}</div></div>`}
function renderTable(rows){$('rowCount').textContent=rows.length;$('mainTable').innerHTML=rows.map((r,i)=>{let s=statusOf(r),d=daysLeft(r),cls=s==='ปกติ'?'normal':s==='ใกล้หมดวาระ'?'soon':'expired';return `<tr><td>${i+1}</td><td>${r.province}</td><td><b>${r.name}</b></td><td>${normExp(r.expertise)}</td><td>${fmt(r.appointed)}</td><td>${fmt(r.expires)}</td><td>${d.toLocaleString()}</td><td><span class="status-pill status-${cls}">${s}</span></td></tr>`}).join('')||'<tr><td colspan="8">ไม่พบข้อมูลตามตัวกรอง</td></tr>'}
function render(){let rows=filtered();renderMap();renderYears(rows);renderExpert(rows);renderTable(rows)}
function clearAll(){Object.keys(state).forEach(k=>state[k]='');['searchProvince','province','expertise','status','duplicate'].forEach(id=>$(id).value='');render()}
fillSelects();renderKpis();renderAlerts();renderDup();render();
$('searchProvince').oninput=e=>{state.search=e.target.value.trim();render()};['province','expertise','status','duplicate'].forEach(id=>$(id).onchange=e=>{state[id]=e.target.value;render()});$('clear').onclick=clearAll;$('resetTop').onclick=clearAll;$('toggleAlerts').onclick=()=>{$('alerts').hidden=!$('alerts').hidden};
